stages:
- test
- build

test_check_code:
  stage: test
  script:
  - echo "Running tests"
  rules:
  - if: $CI_COMMIT_BRANCH == 'main'
    when: never
  - if: $CI_PIPELINE_SOURCE == "push"
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test_build_image:
  stage: test
  image: docker
  services:
  - docker:dind
  script:
  - docker build -t test .
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

build:
  stage: build
  image: docker
  services:
  - docker:dind
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
  - docker pull $CI_REGISTRY_IMAGE:latest || true
  - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" -t "${CI_REGISTRY_IMAGE}:latest" .
  - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
  - docker push $CI_REGISTRY_IMAGE:latest
  rules:
  - if: $CI_COMMIT_BRANCH == 'main'
