mongodb:
  auth:
    rootPassword: "willBeChangedByVault"
    databases:
    - my_database
  persistence:
    enabled: false
  arbiter:
    enabled: false
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false
  initdbScripts:
    createdb.sh: |
      # change to mongo script
      CREATE TABLE IF NOT EXISTS users (
        FirstName text,
        LastName text,
        CreditCard text
