mongodb:
  auth:
    rootPassword: "willBeChangedByVault"
  persistence:
    enabled: false
  arbiter:
    enabled: false
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false
